### PR TITLE
Zone Aggregation

### PR DESCRIPTION
**Pull request by DavidOry**
Placeholder pull request for zone aggregation functionality

### CODE REVIEW

**Comment by DavidOry** [comment]
@jpn--, @JoeJimFlood 
File references have been moved to the [`resources` directory](https://github.com/wsp-sag/client_sandag_rsm_resources). @JoeJimFlood: you should now be able to run the [demo notebook]( https://github.com/SANDAG/RSM/blob/zone-agg/notebooks/ZoneAggDemo.ipynb) if you're interested.

**Comment by JoeJimFlood** [comment]
@DavidOry @jpn-- I tried cloning the zone-agg branch of the repo and wasn't able to run the notebook. It looks like it's failing while the trip list is being loaded. Do I need to run it in Docker? Or is there something else I'm missing?

**Comment by jpn--** [comment]
That's an odd error.  Maybe the trips_sample.pq file somehow got corrupted in the download step?  I'd try deleting it and trying again.  If the same error persists, you can try docker, or we can dig into it tomorrow when we talk

**Comment by JoeJimFlood** [comment]
I had been using an environment that I use for testing things out, but I realized that I should create a new environment based on the yaml file in the repo. After doing that, installing pyarrow, and upgrading scipy it would appear as though the notebook ran through all of the way successfully.

**Comment by DavidOry** [comment]
@jpn--
Can we start over with a new PR or modify this one to back out the hundreds of files committed with the model reference?

**Comment by DavidOry** [comment]
Replaced by #19

**Pull request closed without merging**
